name       : pidgin-sipe
version    : 1.22.0
release    : 6
source     :
    - http://netix.dl.sourceforge.net/project/sipe/sipe/pidgin-sipe-1.22.0/pidgin-sipe-1.22.0.tar.xz : 7fe7e483c0dc2578162a29e7e4e37287b890875fa828516fd353d3c113559ec3
license    : GPL-2.0
component  : network.im
summary    : Pidgin plugin for MS Office Communicator and MS Lync
description: |
    Pidgin plugin for MS Office Communicator and MS Lync
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(farstream-0.2)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gstreamer-rtp-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(nice)
    - pkgconfig(nss)
    - pkgconfig(purple)
    - pkgconfig(telepathy-glib)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
