name       : pidgin-sipe
version    : 1.21.1
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/sipe/sipe/pidgin-sipe-1.21.1/pidgin-sipe-1.21.1.tar.xz : 651af55d65cbdf5bdbee0366bd5151bec4152c910743aa432204d015893fe444
license    : GPL-2.0
component  : network.im
summary    : Pidgin plugin for MS Office Communicator and MS Lync
description: |
    Pidgin plugin for MS Office Communicator and MS Lync
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(nice)
    - pkgconfig(nss)
    - pkgconfig(purple)
    - pkgconfig(telepathy-glib)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
