name       : pidgin-sipe
version    : 1.23.2
release    : 9
source     :
    - https://netix.dl.sourceforge.net/project/sipe/sipe/pidgin-sipe-1.23.2/pidgin-sipe-1.23.2.tar.xz : 9aa05dcc59725f976ce7a88df47a1179927154f27799ab7b8ed8f865f8df0204
license    : GPL-2.0-or-later
component  : network.im
summary    : Pidgin plugin for MS Office Communicator and MS Lync
description: |
    Pidgin plugin for MS Office Communicator and MS Lync
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(farstream-0.2)
    - pkgconfig(gmime-3.0)
    - pkgconfig(gstreamer-rtp-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(nice)
    - pkgconfig(nss)
    - pkgconfig(purple)
    - pkgconfig(telepathy-glib)
setup      : |
    %patch -p1 < $pkgfiles/appshare-fix-black-screen-with-remmina.patch
    %configure
build      : |
    %make
install    : |
    %make_install
